---
title: "Spreading Misinformation"
author: "Bridget Viravouth & Vinny Nguyen"
date: "2025-05-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls()) # to rm all variables from the environment

library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyquery) # for SQL queries in R
library(hexbin)
library(sf)        # for Shapes
library(usmap)     # for the US Map
```

```{r}
df <- read_csv("https://www.ics.uci.edu/~algol/teaching/s2022-IV/fec_2008-2022.csv")

glimpse(df) # like head() but transposes the view

# renaming columns bc easier, feel free to change more col names
df <- df %>%
  rename(Party = Cand_Party_Affiliation,
         Office = Cand_Office)

df$Office[df$Office == "P"] <- "President"
df$Office[df$Office == "S"] <- "Senate"
df$Office[df$Office == "H"] <- "House"
```

```{r}
# RUN THIS CODE! queries and data cleaning

df <- df %>%
  filter(!is.na(Coverage_Start_Date) & !is.na(Coverage_End_Date) & !is.na(Coverage_Start_Date) & !is.na(Cand_Id) & !is.na(Cand_State) & Total_Contribution > 0 & Total_Contribution > 0)

date <- as.Date(df$Coverage_Start_Date, format = "%m/%d/%Y")

years <- as.numeric(format(date, "%Y"))

df$Coverage_Start_Year <- years

q1 <- query("SELECT Party, Total_Contribution, Total_Disbursement
FROM df
WHERE Total_Disbursement > 0 AND Total_Contribution > 0")

q2 <- query("SELECT * FROM q1 WHERE Party = 'DEM' OR Party = 'REP'")

q3 <- query("SELECT Party, Coverage_Start_Year, SUM(Total_Contribution) as Total_Contributions, SUM(Total_Disbursement) as Total_Disbursements
FROM df
WHERE Party = 'DEM' OR Party = 'REP'
GROUP BY Party, Coverage_Start_Year
ORDER BY Coverage_Start_Year")

q4 <- query("SELECT Cand_State as state, COUNT(DISTINCT Cand_Id) as Total_Candidates
FROM df
GROUP BY Cand_State")
```

```{r}
# CONTRIBUTION VS DISBURSEMENT HEXBIN PLOT

ggplot(q1, aes(x = Total_Contribution, y = Total_Disbursement)) +
  stat_density_2d(aes(fill = after_stat(density)), 
                 geom = "raster",
                 contour = FALSE) +
  scale_fill_viridis_c() +
  coord_equal() +
  labs(title = "Total Contribution vs. Total Disbursement",
       subtitle = "Democratic vs Republican Party",
       x = "Total Contribution",
       y = "Total Disbursement",
       fill = "Density") +
  scale_x_log10(labels = scales::label_number(prefix = "$",
                                            big.mark = ",",
                                            accuracy = 1),
                expand = c(0, 0)) +
  scale_y_log10(labels = scales::label_number(prefix = "$",
                                            big.mark = ",",
                                            accuracy = 1),
                expand = c(0, 0)) +
  theme(
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 25, face = "bold"),
    plot.subtitle = element_text(size = 18),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

ggsave("./INF143WhiteRabbit/plots_hw3/WRONG_disburstment_vs_contribution_hex.png", width = 10, height = 6, dpi = 300)
```

```{r}
# CONTRIBUTION VS DISBURSEMENT SCATTER PLOT

ggplot(q2, aes(x = Total_Contribution, y = Total_Disbursement, color = Party)) +
  geom_point(alpha = 0.3) +
  geom_smooth(aes(color = "black"), method = "loess", linewidth = 2,
              na.rm = TRUE, se = FALSE) +
  coord_equal() +
  coord_flip() +
  facet_grid(~ Party) +
  scale_color_manual(values = c("DEM" = "blue", "REP" = "red")) +
  labs(title = "Total Contribution vs. Total Disbursement",
       subtitle = "Democratic (DEM) vs Republican (REP) Party Scatter Plot",
       x = "Total Contribution",
       y = "Total Disbursement") +
  scale_x_log10(labels = scales::label_number(prefix = "$",
                                              big.mark = ",",
                                              accuracy = 1)) +
  scale_y_log10(labels = scales::label_number(prefix = "$",
                                              big.mark = ",",
                                              accuracy = 1)) +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 25, face = "bold"),
    plot.subtitle = element_text(size = 18)
  )

ggsave("./INF143WhiteRabbit/plots_hw3/disburstment_vs_contribution_smooth_scatter.png", width = 10, height = 6, dpi = 300)
```

```{r}
# CONTRIBUTION VS DISBURSEMENT DENSITY PLOT
ggplot(q2, aes(x = Total_Contribution, y = Total_Disbursement, color = Party)) +
  geom_density_2d() +
  facet_wrap(~ Party) +
  scale_color_manual(values = c("DEM" = "blue", "REP" = "red")) +
  coord_equal() +
  coord_flip() +
  labs(title = "Total Contribution vs. Total Disbursement by Party",
       subtitle = "Democratic (DEM) vs Republican (REP) Party Density Plot",
       x = "Total Contribution",
       y = "Total Disbursement") +
  scale_x_log10(labels = scales::label_number(prefix = "$",
                                            big.mark = ",",
                                            accuracy = 1)) +
  scale_y_log10(labels = scales::label_number(prefix = "$",
                                            big.mark = ",",
                                            accuracy = 1)) +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 25, face = "bold"),
    plot.subtitle = element_text(size = 18)
  )

ggsave("./INF143WhiteRabbit/plots_hw3/disburstment_vs_contribution_density.png", width = 10, height = 6, dpi = 300)
```

```{r}
# TIME SERIES PLOT
q3

ggplot(q3, aes(x = Coverage_Start_Year, y = Total_Contributions, color = Party)) + 
  geom_line(size = 1, alpha = 0.7) + 
  geom_vline(xintercept = seq(2007, 2019, by = 4), linetype = "dashed", alpha = 0.3) +
  # PARTY LABELS
  geom_text(data = q3 %>% 
              group_by(Party) %>% 
              filter(Coverage_Start_Year == max(Coverage_Start_Year)),
            aes(label = Party, 
                x = Coverage_Start_Year + 0.7),
            show.legend = FALSE) +
  # IMPORTANT YEAR LABELS
  geom_text(data = q3 %>% 
              filter(Coverage_Start_Year %in% seq(2007, 2019, by = 4)) %>%
              group_by(Coverage_Start_Year) %>%
              summarize(y_pos = max(Total_Contributions)),
            aes(x = Coverage_Start_Year, y = y_pos, 
                label = Coverage_Start_Year),
            color = "black",
            fontface = "bold",
            vjust = -1.5,
            show.legend = FALSE) +
  scale_color_manual(values = c("DEM" = "blue", "REP" = "red")) +
  labs(title = "Total Party Contributions Over Time",
       subtitle = "Republican (REP) vs Democratic (DEM) Party Contributions",
       x = "Year",
       y = "Amount (USD)") + 
  scale_y_log10(labels = scales::label_number(prefix = "$",
                                            big.mark = ",",
                                            accuracy = 1)) +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 25, face = "bold"),
    plot.subtitle = element_text(size = 18),
    legend.position = "none"
  )

ggsave("./INF143WhiteRabbit/plots_hw3/contributions_disbursements_time_series.png", width = 12, height = 10, dpi = 300)
```

```{r}
# chrolopleth map (STATES)
q4

plot_usmap(data = q4, values = "Total_Candidates", regions = "states", include = c("CA", "OR", "WA", "NV", "AK", "HI", "AZ", "UT", "ID")) + 
  scale_fill_continuous(low = "purple", high = "pink", name = "Total Number of Candidates", label = scales::comma) + 
  labs(title = "Canidate Population by West Coast States",
       subtitle = "All political offices taken into consideration.") +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        plot.title = element_text(size = 25, face = "bold"),
        plot.subtitle = element_text(size = 18),
        plot.title.position = "plot",
        legend.position = "bottom",
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))

ggsave("./INF143WhiteRabbit/plots_hw3/chrolopleth_map_states.png", width = 12, height = 8, dpi = 300)

```
